### ISSUE TITLE
VueJS 단 외부 리소스 import 모두 내부로 전환

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/uEngine5-base#36]

**Comment by jinyoung** [comment]
테스트 방법: 네트워크를 끊고 화면에 들어가서 업무를 진행해봄. 이중에서 화면이 나타나지 않거나 하는 브라우저 상의 Not found 오류가 있으면 그게 외부 리소스들임.

**Comment by pinoqio** [comment]
네트워크를 끊어도 브라우저 cache에 의해 정상적인 리소스로 보일 수도 있으니, 브라우저 cache까지 삭제후에 테스트 바랍니다.

**Comment by pinoqio** [comment]
관련 resource external 폴더로 다운로드 후 링크 수정
avatar는 수정되지 않았음

**Comment by pinoqio** [comment]
완료확인
