### ISSUE TITLE
Vue.js에 있는 backend URL 설정값(localhost:8080)이 각 vue마다 설정되어 있는 관계로 수정 시 모든 소스 수정이 요구됨. global value로 적용 바랍니다.

### ISSUE THREAD

**Issue by pinoqio** [TheOpenCloudEngine/uEngine5-base#40]
service-locator 정의 활용

**Comment by jo-narae** [comment]
backend url global value로 처리했습니다.
김영탁 부장님께 컨펌 받는데로 푸쉬하겠습니다.

**Comment by pinoqio** [comment]
나래님 혹 제가 제대로 처리한건지 모르겠네요. 혹 제가 push 한 이후 수정사항 있으시면 push 부탁 드립니다.

**Comment by jo-narae** [comment]
수정하신 부분을 라우터에서 처리하도록 수정했습니다.
push하신 이후에 커밋해서 담당하고 계신 분께 컨펌만 받으면 바로 push하겠습니다.

**Comment by pinoqio** [comment]
완료확인
