### ISSUE TITLE
디자이너 도구모음에 말풍선 형식으로 도구이름 표시

### ISSUE THREAD

**Issue by pinoqio** [TheOpenCloudEngine/uEngine5-base#41]
디자이너 도구모음에 말풍선 형식으로 도구이름 표시. 디자이너 화면 왼쪽 도구모음 및 각 개체의 속성들에도 이름이 표시되어야 함.

**Comment by jinyoung** [comment]
SVG 상에 올리는 처리는 일단 보류.

**Comment by pinoqio** [comment]
디자이너 화면 왼쪽 도구모음에 label 속성 추가 완료
