### ISSUE TITLE
internationalization 다국어처리

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/uEngine5-base#47]
이런걸 쓰면 됨:

1. 페이지에 대한 다국어처리는 일바적 vuejs 의 다국어 처리 프레임워크를 사용:

- vuei18n :  https://kazupon.github.io/vue-i18n/en/
- vuex-i18n 도 있다함.. 
- https://github.com/dkfbasel/vuex-i18n

2. 프로세스 정의 데이터에 대한 다국어 처리는

...

**Comment by pinoqio** [comment]
완료확인
